cp ./Icon.png ./skin/images/Chevron_left.png
cp ./Icon.png ./skin/images/Chevron_left@2x.png
cp ./Icon.png ./skin/images/Chevron_right.png
cp ./Icon.png ./skin/images/Chevron_right@2x.png
cp ./Icon.png ./skin/images/Default_feature-image.png
cp ./Icon.png ./skin/images/Default_feature-image@2x.png
cp ./Icon.png ./skin/images/Profile_favorited.png
cp ./Icon.png ./skin/images/Profile_favorited@2x.png
cp ./Icon.png ./skin/images/Profile_unfavorited.png
cp ./Icon.png ./skin/images/Profile_unfavorited@2x.png
cp ./Icon.png ./skin/images/TabBar_about-active.png
cp ./Icon.png ./skin/images/TabBar_about-active@2x.png
cp ./Icon.png ./skin/images/TabBar_about.png
cp ./Icon.png ./skin/images/TabBar_about@2x.png
cp ./Icon.png ./skin/images/TabBar_details-active.png
cp ./Icon.png ./skin/images/TabBar_details-active@2x.png
cp ./Icon.png ./skin/images/TabBar_details.png
cp ./Icon.png ./skin/images/TabBar_details@2x.png
cp ./Icon.png ./skin/images/TabBar_profile-active.png
cp ./Icon.png ./skin/images/TabBar_profile-active@2x.png
cp ./Icon.png ./skin/images/TabBar_profile.png
cp ./Icon.png ./skin/images/TabBar_profile@2x.png
cp ./Icon.png ./skin/images/TabBar_treemap-active.png
cp ./Icon.png ./skin/images/TabBar_treemap-active@2x.png
cp ./Icon.png ./skin/images/TabBar_treemap.png
cp ./Icon.png ./skin/images/TabBar_treemap@2x.png
cp ./Icon.png ./skin/images/Treemap_Contactbook.png
cp ./Icon.png ./skin/images/Treemap_Contactbook@2x.png
cp ./Icon.png ./skin/images/gps_icon.png
cp ./Icon.png ./skin/images/gps_icon@2x.png
cp ./Icon.png ./skin/images/gps_icon_14.png
cp ./Icon.png ./skin/images/gps_icon_14@2x.png
cp ./Icon.png ./skin/images/handle_icon.png
cp ./Icon.png ./skin/images/handle_icon@2x.png
cp ./Icon.png ./skin/images/location_marker.png
cp ./Icon.png ./skin/images/location_marker@2x.png
cp ./Icon.png ./skin/images/profile.png
cp ./Icon.png ./skin/images/profile@2x.png
cp ./Icon.png ./skin/images/selected_marker.png
cp ./Icon.png ./skin/images/selected_marker@2x.png
cp ./Icon.png ./skin/images/selected_marker_small.png
cp ./Icon.png ./skin/images/selected_marker_small@2x.png 
